add view model
bogdanpoh/ProfileService pull request #2
Opened 2021-01-19 11:38 UTC by bogdanpoh

2021-01-19 11:40 UTC, bohdansasko commented on ProfileService/MainModule/Model/UserModel.swift
> +        let data: [DataResponse]
```suggestion
        var data: [DataResponse]
```

2021-01-19 11:41 UTC, bohdansasko commented on ProfileService/MainModule/Model/UserModel.swift
> +    }
```suggestion
    struct DataResponse: Decodable {
        var id: String
    }
```

2021-01-19 11:42 UTC, bohdansasko commented on ProfileService/MainModule/View/MainView.swift
>      let avatarImage: UIImageView = {
do we need it as public?

2021-01-19 11:42 UTC, bohdansasko commented on ProfileService/MainModule/View/MainView.swift
>      let avatarImage: UIImageView = {
do we need it as public?

2021-01-19 11:42 UTC, bohdansasko commented on ProfileService/MainModule/View/MainView.swift
>      let nickNameLabel: UILabel = {
do we need it as public?

2021-01-19 11:43 UTC, bohdansasko commented on ProfileService/MainModule/View/MainView.swift
> +        }
```suggestion
        switch userModel {
        case .initial:
            updateView(user: nil, isHidden: true)
            
        case .loading:
            updateView(user: nil, isHidden: true)
        
        case .failure:
            updateView(user: nil, isHidden: true)
            
        case .success(let user):
            updateView(user: user, isHidden: false)
        }
```

2021-01-19 11:43 UTC, bohdansasko commented on ProfileService/MainModule/View/MainView.swift
> +        }
what should be here?

2021-01-19 11:44 UTC, bohdansasko commented on ProfileService/MainModule/View/MainViewController.swift
>      }
```suggestion
    func update() {
        mainViewModel?.updateViewData = { [weak self] userModel in
            self?.mainView.userModel = userModel
        }
    }
```

2021-01-19 11:44 UTC, bohdansasko commented on ProfileService/MainModule/View/MainViewController.swift
> +    private var mainViewModel: MainViewModelProtocol?
```suggestion
    private let mainViewModel: MainViewModelProtocol = MainViewModel()
```

2021-01-19 11:44 UTC, bohdansasko commented on ProfileService/MainModule/View/MainViewController.swift
> +        mainViewModel = MainViewModel()
```suggestion
```

2021-01-19 11:45 UTC, bohdansasko commented on ProfileService/MainModule/ViewModel/MainViewModel.swift
> +    var updateViewData: ((UserModel) -> ())? {get set}
```suggestion
    var updateViewData: ((UserModel) -> ())? { get set }
```

2021-01-19 11:47 UTC, bohdansasko commented on ProfileService/MainModule/ViewModel/MainViewModel.swift
> +    }
```suggestion
    func fetchUser(of id: Int) {
        updateViewData?(.loading)
        
        DispatchQueue.main.async { [weak self] in
            // fetched data with network service
            
            self?.updateViewData?(.success(UserModel.User(id: "12457674",
                                                          accountType: "createor",
                                                          mediaCount: 30,
                                                          username: "bogdan.poh",
                                                          media:
                                                            UserModel.MediaDataResponse(data: [
                                                                UserModel.DataResponse(id: "12123156578585"),
                                                                UserModel.DataResponse(id: "1245236347675")
                                                            ]))))
            
        }
    }
```

2021-01-19 11:48 UTC, bogdanpoh commented on ProfileService/MainModule/View/MainViewController.swift
> +    private var mainViewModel: MainViewModelProtocol?
For dependency injection

2021-01-19 11:50 UTC, bohdansasko requested changes

2021-01-19 11:50 UTC, bohdansasko commented on ProfileService/MainModule/ViewModel/MainViewModel.swift
> +    func fetchUser(of id: Int)
in input you should put everything that can input in view model, output -> everything that viewModel returns

2021-01-19 11:53 UTC, bohdansasko commented on ProfileService/MainModule/View/MainView.swift
> +            setNeedsLayout()
why do u call `setNeedsLayout` instead of making own method where u put the whole logic from layoutSubviews?

2021-01-19 13:31 UTC, bohdansasko commented on ProfileService/MainModule/View/MainViewController.swift
> +    func update() {
```suggestion

    func update() {
```

2021-01-19 13:32 UTC, bohdansasko commented on ProfileService/MainModule/ViewModel/MainViewModel.swift
>  }
```suggestion
protocol MainViewModelInput {
    func fetchUser(of id: Int)
}

protocol MainViewModelOutput {
    var updateViewData: ((UserModel) -> ())? { get set }
}
```

2021-01-19 13:33 UTC, bohdansasko commented on ProfileService/MainModule/View/MainView.swift
> +            setNeedsLayout()
```suggestion
why do u  use `setNeedsLayout()`?
```

2021-01-19 13:33 UTC, bohdansasko commented on ProfileService/MainModule/Model/UserModel.swift
> +    case success(User)
btw: what's the purpose of this enumeration?

2021-01-19 13:34 UTC, bohdansasko commented on ProfileService/MainModule/View/MainViewController.swift
> +// MARK: - Private Methods
```suggestion
// MARK: - Updating
```

2021-01-19 13:36 UTC, bohdansasko commented on ProfileService/MainModule/View/MainViewController.swift
> +        update()
`update` shouldn't be called directly from the view. only through the viewModel

2021-01-19 13:37 UTC, bohdansasko requested changes
please, check my questions

2021-01-21 10:27 UTC, bohdansasko approved these changes
Good job! 🥇 :)

2021-01-21 11:01 UTC, merged